version: '3.1'
services:
  db:
    image: postgres:14.1
    restart: 'always'
    environment:
      - POSTGRES_USER=reimar
      - POSTGRES_PASSWORD=reimar
      - POSTGRES_DB=loggia
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - persist_lg:/var/lib/postgresql/data/
      - ./src/database/setup/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  persist_lg: